title: "Should I have become a radiologist? The hype versus reality of radiology AI, AI in general and the road ahead"
description: "20 minute read"
theme: minima

url: "https://ameyarad.github.io"
baseurl: "/RadiologyAI"

plugins:
  - jekyll-feed
