title: "Should I have become a radiologist? The hype versus reality of radiology AI, AI in general and the road ahead"
description: "Ameya Kawthalkar"
theme: jekyll-theme-minimal

url: "https://ameyarad.github.io"
baseurl: "/RadiologyAI"

plugins:
  - jekyll-feed

host: 0.0.0.0
port: 5000
